### ISSUE TITLE
Do you have any plans to continue development?

### ISSUE THREAD

**Issue by riseremi** [joshwcomeau/yoyocollect#1]
Hey, thank you for the app. My question is in the subject :)

**Comment by joshwcomeau** [comment]
> Hey, thank you for the app. My question is in the subject :)

Afraid not, sorry =( I haven't thought about this project in years!

If you're looking for something to manage collections, I find AirTable really useful.

Sorry for the delay!

**Comment by riseremi** [comment]
Oh thank you. I'll look into AirTable then :)
